export const translations = {
    english: {
      appName: "EzziMart",
      tagline: "Your ultimate destination for groceries, electronics, fashion, and more.",
      login: "Login to Get Started",
      language: "Language",
      offers: "Today's Offers",
      groceriesOffer: "10% off on orders above ₹500",
      fashionOffer: "20% off on fashion and accessories",
      electronicsOffer: "Flat 30% off on electronics this weekend",
      groceriesBOGO: "Buy 1 Get 1 Free on select groceries",
      categories: "Explore Categories",
      groceries: "Groceries",
      groceriesDesc: "Fresh vegetables, fruits, and daily essentials.",
      fashion: "Fashion",
      fashionDesc: "Latest trends in clothing, shoes, and accessories.",
      electronics: "Electronics",
      electronicsDesc: "Smartphones, laptops, and home appliances.",
      jewelry: "Jewelry",
      jewelryDesc: "Elegant gold, silver, and diamond pieces.",
      faq: "Frequently Asked Questions",
      faq1: "What is EzziMart?",
      faq2: "What offers are available?",
      faq3: "What can I buy?",
      faq4: "How do I track my order?",
    },
    hindi: {
      appName: "इज्ज़ीमार्ट",
      tagline: "आपकी खरीदारी की अंतिम मंज़िल: किराने का सामान, इलेक्ट्रॉनिक्स, फैशन और बहुत कुछ।",
      login: "शुरू करने के लिए लॉगिन करें",
      language: "भाषा",
      offers: "आज के ऑफर",
      groceriesOffer: "₹500 से अधिक के ऑर्डर पर 10% छूट",
      fashionOffer: "फैशन और एसेसरीज पर 20% छूट",
      electronicsOffer: "इस सप्ताहांत इलेक्ट्रॉनिक्स पर फ्लैट 30% छूट",
      groceriesBOGO: "चुनिंदा किराने के सामान पर 1 खरीदें 1 मुफ्त पाएं",
      categories: "श्रेणियाँ देखें",
      groceries: "किराना",
      groceriesDesc: "ताज़ी सब्जियाँ, फल, और दैनिक आवश्यकताएं।",
      fashion: "फैशन",
      fashionDesc: "कपड़े, जूते, और एसेसरीज के नवीनतम ट्रेंड।",
      electronics: "इलेक्ट्रॉनिक्स",
      electronicsDesc: "स्मार्टफोन, लैपटॉप, और होम एप्लायंसेस।",
      jewelry: "आभूषण",
      jewelryDesc: "आकर्षक सोने, चांदी और हीरे के गहने।",
      faq: "सामान्य प्रश्न",
      faq1: "इज्ज़ीमार्ट क्या है?",
      faq2: "कौन से ऑफर उपलब्ध हैं?",
      faq3: "मैं क्या खरीद सकता/सकती हूँ?",
      faq4: "मैं अपना ऑर्डर कैसे ट्रैक करूँ?",
    },
  };
  